### ISSUE TITLE
Memory hungry

### ISSUE THREAD

**Issue by santids** [cgat-developers/ruffus#122]
I've been using this for a couple of days and it's eating all my ram freezing my computer. Maybe there is an optimization to avoid using all that memory.

**Comment by IanSudbery** [comment]
There are some tips for reducing memory usage on the documentation site:
https://umi-tools.readthedocs.io/en/latest/faq.html

For most samples, if you are running without `--output-stats` and you are remember to include `--per-cell` if you are doing single cell work, deduplication should use less memory than read alignment does. If you are using paired end sequencing and have a lot of reads where the two ends map to different chromosomes, you can also save memory with `--chimeric-reads=discard`, but you will then loose all those reads where the two ends map to different chromosomes. 

However, for some samples with very large UMI networks there is just no way around the fact that the job is memory requiring. In order to compute an process a network of 20,000 UMIs at one location for example, it might be necessary to store up to 400 million connections.
